# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: docker:stable-git

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip
            pip install awscli

      - run:
          name: Build docker image
          command: |
            docker build -t $AWS_ACCOUNT.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/api-test:$CIRCLE_TAG+$CIRCLE_SHA1 .

workflows:
  version: 2
  tagged-build:
    jobs:
      - build:
          context: AWS-bassham-us-east-1
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(\d+)\.(\d+)\.(\d+)(-rc\.\d+)?$/

# ^v(\d+)\.(\d+)\.(\d+)(-rc\.\d+)?(\+[0-9A-F]+)?(\.[0-9]+)?$